networks:
  my_network:
    driver: bridge
    name: my_network

services:
  nifi:
    container_name: nifi-ingestion
    build: ./nifi/nifi-ingestion/
    hostname: nifi-ingestion
    ports:
      - '8443:8443'
    networks:
      - my_network
    tty: true
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_HOME=/opt/nifi/nifi-current
      - NIFI_SENSITIVE_PROPS_KEY=aUXli7kVGgb6egfNFUca7Rb7yurCrZxTYULdx3bM5kU=
    volumes:
      - ./nifi/nifi-ingestion/dataset:/opt/nifi/nifi-current/dataset
    depends_on: 
      - hdfs-master

  ## HDFS
  hdfs-master :
    container_name: master
    working_dir: /scripts
    hostname: master
    image: matnar/hadoop
    ports:
      - "54310:54310"
    networks:
      - my_network
    tty: true
    volumes:
    - ./hadoop:/scripts
    depends_on:
      - slave1
    

  slave1 :
    container_name: hdfs-worker1
    image: matnar/hadoop
    ports:
      - "9864:9864"
    networks:
      - my_network
    tty: true
    depends_on:
      - slave2

  slave2:
    container_name: hdfs-worker2
    image: matnar/hadoop
    ports:
      - "9863:9864"
    networks:
      - my_network
    tty: true
    depends_on:
      - slave3

  slave3:
    container_name: hdfs-worker3
    image: matnar/hadoop
    ports:
      - "9862:9864"
    networks:
      - my_network
    tty: true


  ## Spark
  # spark-master:
  #   image: bitnami/spark
  #   environment:
  #     - SPARK_MODE=master
  #   networks:
  #     - my_network
  #   hostname: spark-master
  #   ports:
  #     - 8080:8080
  #   tty: true

  # spark-worker:
  #   image: bitnami/spark
  #   networks:
  #     - my_network
  #   environment:
  #     - SPARK_MODE=worker
  #   tty: true
  #   depends_on:
  #     - spark-master
  #   deploy:
  #     replicas: 2