networks:
  batch_processing_network:
    driver: bridge
    name: batch_processing_network

services:
  
  ## NIFI
  nifi:
    container_name: nifi-ingestion
    build: ./nifi/nifi-ingestion/
    hostname: nifi-ingestion
    ports:
      - '8443:8443'
    networks:
      - batch_processing_network
    tty: true
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_HOME=/opt/nifi/nifi-current
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
    volumes:
      - ./nifi/nifi-ingestion/dataset:/opt/nifi/nifi-current/dataset
    depends_on: 
      - hdfs-master

  ## HDFS
  hdfs-master :
    container_name: hdfs-master
    working_dir: /scripts
    hostname: master
    image: matnar/hadoop
    ports:
      - "54310:54310"
    networks:
      - batch_processing_network
    tty: true
    volumes:
    - ./hadoop:/scripts
    depends_on:
      - slave1
    
  slave1 :
    container_name: hdfs-worker1
    image: matnar/hadoop
    ports:
      - "9864:9864"
    networks:
      - batch_processing_network
    tty: true
    depends_on:
      - slave2

  slave2:
    container_name: hdfs-worker2
    image: matnar/hadoop
    ports:
      - "9863:9864"
    networks:
      - batch_processing_network
    tty: true
    depends_on:
      - slave3

  slave3:
    container_name: hdfs-worker3
    image: matnar/hadoop
    ports:
      - "9862:9864"
    networks:
      - batch_processing_network
    tty: true
    depends_on:
      - spark-master

  ## SPARK
  spark-master:
    container_name: spark-master
    image: bitnami/spark
    environment:
      - SPARK_MODE=master
    networks:
      - batch_processing_network
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    tty: true
    depends_on:
      - spark-worker

  spark-worker:
    image: bitnami/spark
    networks:
      - batch_processing_network
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    tty: true

  # spark-worker2:
  #   container_name: spark-worker2
  #   image: bitnami/spark
  #   networks:
  #     - batch_processing_network
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #   tty: true
  #   depends_on:
  #     - redis
      
  ## REDIS
  redis:
    container_name: redis
    image: redis
    networks:
      - batch_processing_network
    ports:
      - "6379:6379"
    tty: true
  
  ## GRAFANA
  grafana:
    container_name: grafana
    build: ./grafana/
    image: custom-grafana
    ports:
      - "3000:3000"
    networks:
      - batch_processing_network
    environment:
      - GF_SECURITY_ADMIN_USER={$GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD={$GRAFANA_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - redis

volumes:
  grafana-storage:
