services:
  ## NIFI
  nifi:
    container_name: nifi-ingestion
    build: ./nifi/nifi-ingestion/
    hostname: nifi-ingestion
    ports:
      - '8443:8443'
    networks:
      - batch_processing_network
    tty: true
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_HOME=/opt/nifi/nifi-current
      - NIFI_SENSITIVE_PROPS_KEY=aUXli7kVGgb6egfNFUca7Rb7yurCrZxTYULdx3bM5kU=
    volumes:
      - ./nifi/nifi-ingestion/dataset:/opt/nifi/nifi-current/dataset
    depends_on: 
      - hdfs-master

  ## HDFS
  hdfs-master :
    container_name: hdfs-master
    working_dir: /scripts
    hostname: master
    image: matnar/hadoop
    ports:
      - "54310:54310"
    networks:
      - batch_processing_network
    tty: true
    volumes:
    - ./hadoop:/scripts
    depends_on:
      - slave1
    

  slave1 :
    container_name: hdfs-worker1
    image: matnar/hadoop
    ports:
      - "9864:9864"
    networks:
      - batch_processing_network
    tty: true
    depends_on:
      - slave2

  slave2:
    container_name: hdfs-worker2
    image: matnar/hadoop
    ports:
      - "9863:9864"
    networks:
      - batch_processing_network
    tty: true
    depends_on:
      - slave3

  slave3:
    container_name: hdfs-worker3
    image: matnar/hadoop
    ports:
      - "9862:9864"
    networks:
      - batch_processing_network
    tty: true

  ## SPARK
  spark-master:
    container_name: spark-master
    image: bitnami/spark
    environment:
      - SPARK_MODE=master
    networks:
      - batch_processing_network
    hostname: spark-master
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - spark-worker1

  spark-worker1:
    container_name: spark-worker1
    image: bitnami/spark
    networks:
      - batch_processing_network
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    tty: true
    depends_on:
      - spark-worker2

  spark-worker2:
    container_name: spark-worker2
    image: bitnami/spark
    networks:
      - batch_processing_network
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    tty: true

networks:
  batch_processing_network:
    driver: bridge
    name: batch_processing_network