apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    url: redis://redis:6379
    isDefault: true
    jsonData:
      dataSourceType: REDIS_TIMESERIES
